In [2]:
# Load excel data
import pandas as pd
df =pd.read_excel("sale_data.xlsx")

In [3]:
df

     Order_ID           Order_Date Customer Region  Product  Sales   Cost
0        1001            1/13/2023    Rohit  South   Mobile  23289  19118
1        1002  2023-07-10 00:00:00     Aman   West   Laptop   8905   5593
2        1003  2023-05-11 00:00:00    Rahul  South  Monitor  59987  39959
3        1004            2/19/2024    Rahul  South  Printer  49597  33892
4        1005            1/26/2024   Anjali  North   Laptop  54797  34468
..        ...                  ...      ...    ...      ...    ...    ...
515      1389  2024-12-02 00:00:00    Vikas  North   Laptop  17924  12145
516      1496            4/24/2023    Kiran  North  Printer  23434  16388
517      1031            2/19/2023    Vikas   East  Printer  58883  43579
518      1317  2023-05-07 00:00:00     Aman  North   Laptop  76781  66865
519      1409            1/16/2024    Pooja  North  Monitor  19969  13586

[520 rows x 7 columns]

In [5]:
#check the duplicated value
df.duplicated().sum()

np.int64(20)

In [6]:
# Remove duplicate value
df=df.drop_duplicates()

In [28]:
df

     Order_ID           Order_Date Customer Region  Product  Sales   Cost
0        1001            1/13/2023    Rohit  South   Mobile  23289  19118
1        1002  2023-07-10 00:00:00     Aman   West   Laptop   8905   5593
2        1003  2023-05-11 00:00:00    Rahul  South  Monitor  59987  39959
3        1004            2/19/2024    Rahul  South  Printer  49597  33892
4        1005            1/26/2024   Anjali  North   Laptop  54797  34468
..        ...                  ...      ...    ...      ...    ...    ...
495      1496            4/24/2023    Kiran  North  Printer  23434  16388
496      1497            6/27/2023   Anjali  South   Laptop  49007  35970
497      1498  2023-08-05 00:00:00     Aman   East   Tablet  19160  15636
498      1499                  NaN    Pooja   West   Mobile  59266  44326
499      1500  2023-07-10 00:00:00    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
#fill blank
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

In [9]:
# Remove NaT from data 
df=df.dropna(subset=['Order_Date'])

In [10]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-07-10     Aman   West   Laptop   8905   5593
2        1003 2023-05-11    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-08-05     Aman   East   Tablet  19160  15636
499      1500 2023-07-10    Vikas  North  Printer  34567  22426

[482 rows x 7 columns]

In [11]:
# Create column for the profit, Year Month and day
df['Profit']=df['Sales']-df['Cost']
df['Day']=df['Order_Date'].dt.day
df['Month']=df['Order_Date'].dt.month
df['Year']=df['Order_Date'].dt.year

In [12]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Day,Month,Year
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,13,1,2023
1,1002,2023-07-10,Aman,West,Laptop,8905,5593,3312,10,7,2023
2,1003,2023-05-11,Rahul,South,Monitor,59987,39959,20028,11,5,2023
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,19,2,2024
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,26,1,2024
...,...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,18,10,2023
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,24,4,2023
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,27,6,2023
497,1498,2023-08-05,Aman,East,Tablet,19160,15636,3524,5,8,2023
499,1500,2023-07-10,Vikas,North,Printer,34567,22426,12141,10,7,2023

In [13]:
# save data as a csv file
df.to_csv('Sales_cleaned_data.csv',index=False)

In [14]:
#create connection b/w excel python and sql
import pandas as pd
from sqlalchemy import create_engine

In [16]:
# load csv file
df=pd.read_csv("Sales_cleaned_data.csv")

In [17]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Day,Month,Year
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,13,1,2023
1,1002,2023-07-10,Aman,West,Laptop,8905,5593,3312,10,7,2023
2,1003,2023-05-11,Rahul,South,Monitor,59987,39959,20028,11,5,2023
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,19,2,2024
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,26,1,2024
...,...,...,...,...,...,...,...,...,...,...,...
477,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,18,10,2023
478,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,24,4,2023
479,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,27,6,2023
480,1498,2023-08-05,Aman,East,Tablet,19160,15636,3524,5,8,2023
481,1500,2023-07-10,Vikas,North,Printer,34567,22426,12141,10,7,2023

In [27]:
# create engine
engine = create_engine(
    "mysql+pymysql://root:root@localhost:3306/salesdb"
)

In [28]:
#put the data in mysql
df.to_sql(name="salesdata",con=engine,if_exists='replace',index=False)

482